# Generated by Django 4.2 on 2023-08-29 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_titl_share_title_share_recipeowner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='hastags',
        ),
        migrations.RemoveField(
            model_name='share',
            name='title',
        ),
        migrations.AddField(
            model_name='recipe',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
