# Generated by Django 4.2 on 2023-08-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_recipe_hastags_remove_share_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='hashtags',
            new_name='hastags',
        ),
    ]
