# Generated by Django 4.2 on 2023-08-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_hashtags_recipe_hastags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shareId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_recipes', to='myapp.share'),
        ),
    ]
