# Generated by Django 4.2 on 2023-08-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_share_recipe_shareid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='reacter',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='shareId',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recipemedia',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='share',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='share',
            name='recipeOwner',
        ),
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeMedia',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
