# Generated by Django 4.2 on 2023-08-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
        migrations.AlterField(
            model_name='share',
            name='recipeOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
