# Generated by Django 4.2 on 2023-08-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_share_user_alter_share_recipeowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
