# Generated by Django 4.2 on 2023-08-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_recipe_description_alter_recipe_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='shareId',
        ),
    ]
