# Generated by Django 4.2 on 2023-08-30 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followee',
        ),
        migrations.AddField(
            model_name='follow',
            name='you',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='you', to='myapp.user'),
        ),
    ]
