# Generated by Django 4.2 on 2023-08-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_follow_followee_follow_you'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='you',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follo', to='myapp.user'),
        ),
    ]
