# Generated by Django 4.2 on 2023-09-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_reporttorecipe_blockuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttorecipe',
            name='reporterId',
        ),
        migrations.AddField(
            model_name='reporttorecipe',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
