# Generated by Django 4.2 on 2023-09-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_reporttorecipe_reporterid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttorecipe',
            name='reporterId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
